### ISSUE TITLE
Syntax highlightning not working

### ISSUE THREAD

**Issue by zmcddn** [avivace/monokaiC#2]
Hi, thanks a lot for the theme, I really like it.

However, the syntax highlighting is not working for me, I followed the readme file to use the theme and everything works fine except for the syntax highlighting. 
![image](https://user-images.githubusercontent.com/33881108/47518346-f933cf80-d847-11e8-8755-52cf97a138a1.png)

I'm using sublimetext 3 on win 10 64 bit os, thanks!

**Comment by avivace** [comment]
Oh hey! Glad you are enjoying the theme!
Try to enable the theme in _Markdown GFM Settings - User_, then set the file syntax as _MarkdownEditing -> Markdown GFM_

**Comment by zmcddn** [comment]
@avivace thanks for your rapid response! It worked!

My setting was setup with syntax -> MarkdownEditing -> Markdown and the syntax highlighting doesn't work. Then I followed what you suggested and use Markdown GFM and it worked. Any explanations?

Plus, maybe you can update your ReadMe file accordingly? 

Much appreciated!

**Comment by avivace** [comment]
Yep! It makes sense
