### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by seantronathon** [avivace/monokaiC#3]
Hi there.

Love this color scheme, and I'm bummed it's not working for me. Does it work for Windows?

I'm getting a popup error that reads:

Error loading colour scheme
Packages/User/ME-MonokaiC.tmTheme: Error parsing plist
xml: expected = in file Packages/User/ME-MonokaiC.tmTheme
on line: 44

**Comment by avivace** [comment]
It definitely works on Windows.
Install MarkdownEditing first, using the Package Control then, copy the theme in `%appdata%\Sublime Text 3\Packages\User` then enable it as suggested in the README.

![image](https://user-images.githubusercontent.com/14352721/47719748-5b2b7500-dc4c-11e8-9a13-ca4dac91ac2b.png)

**Comment by seantronathon** [comment]
Thanks. Yeah. Sorry. I flubbed the copy process, so the file I ended up with was fundamentally the wrong file. Works great now!

**Comment by avivace** [comment]
No problem at all! Took the chance to update the instructions for Windows.

Keep up the good work!
